# Generated by Django 3.2.3 on 2021-06-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('room_name',),
            },
        ),
    ]
