# Generated by Django 3.2.3 on 2021-06-14 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channel', '0002_joinchatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinchatroom',
            name='room_id',
            field=models.CharField(max_length=255, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
