# Generated by Django 3.2 on 2021-07-09 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channel', '0006_alter_chatroomchannel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomchannel',
            name='room_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'You can input only alphabets or numbers.')]),
        ),
        migrations.AlterField(
            model_name='joinchatroom',
            name='room_id',
            field=models.CharField(max_length=19),
        ),
    ]
